# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f30f5af3e3d61f5bb7b9ddc70d69c4a1756261cadfb093932537712196496cdb5e68020739b6ca97ff8521f7d8b6d181de59eadfef2d64210dced239f696ae2

test:
  secret_key_base: 8bcc06373b9f3b86e4c2a47028d8537a90c42cebb08e8951373dbb6febc0a3c295b255c0f728be40a86f0f8bb0a8ef1560f8beb44df35e2ca2717df8deb43422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
